---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netdata-conf-master
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $name, $config := .Values.master.configs }}
  {{- if $config.enabled }}
  {{ $name }}: {{ toYaml $config.data | indent 4 }}
  {{- end }}
  {{- end }}

---

{{- if .Values.slave.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: netdata-conf-slave
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $name, $config := .Values.slave.configs }}
  {{- if $config.enabled }}
  {{ $name }}: {{ toYaml $config.data | indent 4 }}
  {{- end }}
  {{- end }}
{{- end }}

---

{{- if and (.Values.slave.enabled) (.Values.slave.sd.enabled) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.slave.sd.cmap_name}}
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ .Values.slave.sd.cmap_key }}: |
  {{- .Files.Get .Values.slave.sd.file | nindent 4 }}
{{- end }}
