---
apiVersion: v1
kind: ConfigMap
metadata:
  name: netdata-conf-master
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $name, $config := .Values.master.configs }}
  {{- if $config.enabled }}
  {{ $name }}: {{ toYaml $config.data | indent 4 }}
  {{- end }}
  {{- end }}

---

{{- if .Values.slave.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: netdata-conf-slave
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $name, $config := .Values.slave.configs }}
  {{- if $config.enabled }}
  {{ $name }}: {{ toYaml $config.data | indent 4 }}
  {{- end }}
  {{- end }}
{{- end }}

---

{{- if and (.Values.slave.enabled) (.Values.sd.slave.enabled) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.sd.slave.cmap_name}}
  labels:
    app: {{ template "netdata.name" . }}
    chart: {{ template "netdata.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ .Values.sd.slave.cmap_key }}: |
    {{- with .Values.sd.slave.config }}
    name: {{ .name }}
    discovery: {{ toYaml .discovery | nindent 6 }}
    tag: {{ toYaml .tag | nindent 6 }}
    build: {{ toYaml .build | nindent 6 }}
    export: {{ toYaml .export | nindent 6 }}
    {{- end }}
{{- end }}
